version: '3.7'
services:
  spaceapi:
    image: spaceapi
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.spaceapi.loadbalancer.server.port=8000" 
        - "traefik.http.routers.spaceapi.rule=Host(`spaceapi.flipdot.dev`)"
        - "traefik.http.routers.spaceapi.tls=true"
        - "traefik.http.routers.spaceapi.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    external: true
